// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductService.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ECommerce.Contracts {

  /// <summary>Holder for reflection information generated from ProductService.proto</summary>
  public static partial class ProductServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for ProductService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProductServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRQcm9kdWN0U2VydmljZS5wcm90bxITRUNvbW1lcmNlLkNvbnRyYWN0cyJX",
            "ChpHZXRQcm9kdWN0c0J5RmFtaWx5UmVxdWVzdBI5Cg1Qcm9kdWN0RmFtaWx5",
            "GAEgASgOMiIuRUNvbW1lcmNlLkNvbnRyYWN0cy5Qcm9kdWN0RmFtaWx5IkUK",
            "E0dldFByb2R1Y3RzUmVzcG9uc2USLgoIUHJvZHVjdHMYASADKAsyHC5FQ29t",
            "bWVyY2UuQ29udHJhY3RzLlByb2R1Y3QiXwoHUHJvZHVjdBIRCglQcm9kdWN0",
            "SWQYASABKAMSEwoLUHJvZHVjdE5hbWUYAiABKAkSLAoGQWRkT25zGAMgAygL",
            "MhwuRUNvbW1lcmNlLkNvbnRyYWN0cy5Qcm9kdWN0IgcKBUVtcHR5Kk0KDVBy",
            "b2R1Y3RGYW1pbHkSFQoRQ29sbGFib3JhdGlvblRvb2wQABISCg5Db25mZXJl",
            "bmNlQ2FsbBABEhEKDVNjcmVlblNoYXJpbmcQAjLbAQoOUHJvZHVjdFNlcnZp",
            "Y2UScgoTR2V0UHJvZHVjdHNCeUZhbWlseRIvLkVDb21tZXJjZS5Db250cmFj",
            "dHMuR2V0UHJvZHVjdHNCeUZhbWlseVJlcXVlc3QaKC5FQ29tbWVyY2UuQ29u",
            "dHJhY3RzLkdldFByb2R1Y3RzUmVzcG9uc2UiABJVCgtHZXRQcm9kdWN0cxIa",
            "LkVDb21tZXJjZS5Db250cmFjdHMuRW1wdHkaKC5FQ29tbWVyY2UuQ29udHJh",
            "Y3RzLkdldFByb2R1Y3RzUmVzcG9uc2UiAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ECommerce.Contracts.ProductFamily), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ECommerce.Contracts.GetProductsByFamilyRequest), global::ECommerce.Contracts.GetProductsByFamilyRequest.Parser, new[]{ "ProductFamily" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ECommerce.Contracts.GetProductsResponse), global::ECommerce.Contracts.GetProductsResponse.Parser, new[]{ "Products" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ECommerce.Contracts.Product), global::ECommerce.Contracts.Product.Parser, new[]{ "ProductId", "ProductName", "AddOns" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ECommerce.Contracts.Empty), global::ECommerce.Contracts.Empty.Parser, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ProductFamily {
    [pbr::OriginalName("CollaborationTool")] CollaborationTool = 0,
    [pbr::OriginalName("ConferenceCall")] ConferenceCall = 1,
    [pbr::OriginalName("ScreenSharing")] ScreenSharing = 2,
  }

  #endregion

  #region Messages
  public sealed partial class GetProductsByFamilyRequest : pb::IMessage<GetProductsByFamilyRequest> {
    private static readonly pb::MessageParser<GetProductsByFamilyRequest> _parser = new pb::MessageParser<GetProductsByFamilyRequest>(() => new GetProductsByFamilyRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetProductsByFamilyRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ECommerce.Contracts.ProductServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetProductsByFamilyRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetProductsByFamilyRequest(GetProductsByFamilyRequest other) : this() {
      productFamily_ = other.productFamily_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetProductsByFamilyRequest Clone() {
      return new GetProductsByFamilyRequest(this);
    }

    /// <summary>Field number for the "ProductFamily" field.</summary>
    public const int ProductFamilyFieldNumber = 1;
    private global::ECommerce.Contracts.ProductFamily productFamily_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ECommerce.Contracts.ProductFamily ProductFamily {
      get { return productFamily_; }
      set {
        productFamily_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetProductsByFamilyRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetProductsByFamilyRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ProductFamily != other.ProductFamily) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ProductFamily != 0) hash ^= ProductFamily.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ProductFamily != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ProductFamily);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ProductFamily != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ProductFamily);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetProductsByFamilyRequest other) {
      if (other == null) {
        return;
      }
      if (other.ProductFamily != 0) {
        ProductFamily = other.ProductFamily;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            productFamily_ = (global::ECommerce.Contracts.ProductFamily) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetProductsResponse : pb::IMessage<GetProductsResponse> {
    private static readonly pb::MessageParser<GetProductsResponse> _parser = new pb::MessageParser<GetProductsResponse>(() => new GetProductsResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetProductsResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ECommerce.Contracts.ProductServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetProductsResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetProductsResponse(GetProductsResponse other) : this() {
      products_ = other.products_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetProductsResponse Clone() {
      return new GetProductsResponse(this);
    }

    /// <summary>Field number for the "Products" field.</summary>
    public const int ProductsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::ECommerce.Contracts.Product> _repeated_products_codec
        = pb::FieldCodec.ForMessage(10, global::ECommerce.Contracts.Product.Parser);
    private readonly pbc::RepeatedField<global::ECommerce.Contracts.Product> products_ = new pbc::RepeatedField<global::ECommerce.Contracts.Product>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ECommerce.Contracts.Product> Products {
      get { return products_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetProductsResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetProductsResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!products_.Equals(other.products_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= products_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      products_.WriteTo(output, _repeated_products_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += products_.CalculateSize(_repeated_products_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetProductsResponse other) {
      if (other == null) {
        return;
      }
      products_.Add(other.products_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            products_.AddEntriesFrom(input, _repeated_products_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Product : pb::IMessage<Product> {
    private static readonly pb::MessageParser<Product> _parser = new pb::MessageParser<Product>(() => new Product());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Product> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ECommerce.Contracts.ProductServiceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Product() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Product(Product other) : this() {
      productId_ = other.productId_;
      productName_ = other.productName_;
      addOns_ = other.addOns_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Product Clone() {
      return new Product(this);
    }

    /// <summary>Field number for the "ProductId" field.</summary>
    public const int ProductIdFieldNumber = 1;
    private long productId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long ProductId {
      get { return productId_; }
      set {
        productId_ = value;
      }
    }

    /// <summary>Field number for the "ProductName" field.</summary>
    public const int ProductNameFieldNumber = 2;
    private string productName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ProductName {
      get { return productName_; }
      set {
        productName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "AddOns" field.</summary>
    public const int AddOnsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::ECommerce.Contracts.Product> _repeated_addOns_codec
        = pb::FieldCodec.ForMessage(26, global::ECommerce.Contracts.Product.Parser);
    private readonly pbc::RepeatedField<global::ECommerce.Contracts.Product> addOns_ = new pbc::RepeatedField<global::ECommerce.Contracts.Product>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ECommerce.Contracts.Product> AddOns {
      get { return addOns_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Product);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Product other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ProductId != other.ProductId) return false;
      if (ProductName != other.ProductName) return false;
      if(!addOns_.Equals(other.addOns_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ProductId != 0L) hash ^= ProductId.GetHashCode();
      if (ProductName.Length != 0) hash ^= ProductName.GetHashCode();
      hash ^= addOns_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ProductId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(ProductId);
      }
      if (ProductName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ProductName);
      }
      addOns_.WriteTo(output, _repeated_addOns_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ProductId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ProductId);
      }
      if (ProductName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ProductName);
      }
      size += addOns_.CalculateSize(_repeated_addOns_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Product other) {
      if (other == null) {
        return;
      }
      if (other.ProductId != 0L) {
        ProductId = other.ProductId;
      }
      if (other.ProductName.Length != 0) {
        ProductName = other.ProductName;
      }
      addOns_.Add(other.addOns_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            ProductId = input.ReadInt64();
            break;
          }
          case 18: {
            ProductName = input.ReadString();
            break;
          }
          case 26: {
            addOns_.AddEntriesFrom(input, _repeated_addOns_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Empty : pb::IMessage<Empty> {
    private static readonly pb::MessageParser<Empty> _parser = new pb::MessageParser<Empty>(() => new Empty());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Empty> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ECommerce.Contracts.ProductServiceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Empty() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Empty(Empty other) : this() {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Empty Clone() {
      return new Empty(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Empty);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Empty other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Empty other) {
      if (other == null) {
        return;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
